markdown: redcarpet
pygments: true

# Permalinks
permalink:        pretty

# Setup
title:            \"Escaping Reality\"
description:      'Thoughts from a crazy person'
url:              http://brendan.berman.io

author:           'pcflmb'
name:           'Brendan Berman'
url:            

paginate:         5

# Custom vars
version:          1.0.10

github:  https://github.com/pcflmb
