# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            \x2F\x22Escaping Reality\x2F\x22'
tagline:          
description:      'Thoughts from a crazy person'
url:              http://brendan.berman.io

author:           
  name:           'Brendan Berman'
  url:            

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/pcflmb
